name: feature-branch
on:
  push:
    branches:
      - '!master'
jobs:
  check-bats-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install
        uses: actions/setup-node@v3
        run: npm run install
      - name: Test
        run: npm run test
